[pytest]
norecursedirs = $RECYCLE.BIN $Recycle.Bin System Volume Information .git .svn .hg
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = --ignore=tests/test_nlm_query.py --ignore=tests/test_nlm_scraper.py --ignore=tests/test_nlm_exporter.py
